mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.sre.analysis.mapper: DEBUG

#spring:
#      # yml配置的优先级高于java配置；如果yml配置和java配置同时存在，则yml配置会覆盖java配置
#  http-client:
#    pool:
#          #连接池的最大连接数，0代表不限；如果取0，需要考虑连接泄露导致系统崩溃的后果
#      maxTotalConnect: 3

#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    platform: mysql
#    url: jdbc:mysql://10.142.70.250:3306/analysis?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123123
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT1FROMDUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    filters: stat,wall,log4j
#    logSlowSql: true